# Base configs
baseurl: "https://avi-141.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Weddings by Gala Events"
subtitle: "Every detail matters. Bringing dreams to life!"
author: "Gala Events"
header:
 title: "Wedding photography"
 subtitle: "by Gala Events"
footer:
 name: "Gala Events- End to End Wedding Planner"
 bio: "We handle End to End weddings all around the world.
 Contact us at "
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/Galaeventmanagers"
  #twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/gala.weddings"
  youtube:   "https://www.youtube.com/channel/UCFL5WUt1q-jjg3Y9AlGyizA"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/manisha-mehta-19565884"
  #github: "https://www.github.com/rampatra"
