# Base configs
baseurl: "https://avi-141.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Weddings by Gala Events"
subtitle: "Every detail matters. Bringing dreams to life!"
author: "Gala Events"
header:
 title: "Gala Events"
 subtitle: "Email:galaendeavours@gmail.com Ph: 9000660869"
footer:
 name: "Gala Events- End to End Wedding Planner"
 bio: "The Gala Events - Who we are :
The Gala Events is an "End to End Wedding Planning and Management Company",  born out of passion for creativity and making Dreams come true in the year 2013.
Every detail matters. And we at Gala Events understand this. It reflects in our meticulous planning and execution.
Gala Events is known for its high professionalism, customer centric service and event delivery strategy. We offer "A wow-factor", no guest will ever forget!
Our experience of 8 years in the industry, along with extensive research and exposure creates an experience that will remain etched in the minds of everyone who is part of it.
We handle End to End Wedding planning and management-PAN INDIA.
Our experienced and dedicated  team makes sure that your spectacular Wedding involves immaculate and intricate planning, creative conceptualization, design and flawless execution.
We are your dream team.
"Bringing your Gala dreams to life"
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "Gala Events"
social_urls:
  facebook: "https://www.facebook.com/Galaeventmanagers"
  #twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/gala.weddings"
  youtube:   "https://www.youtube.com/channel/UCFL5WUt1q-jjg3Y9AlGyizA"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/manisha-mehta-19565884"
  #github: "https://www.github.com/rampatra"
