# Base configs
baseurl: "https://avi-141.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Weddings by Gala Events"
subtitle: "Every detail matters. Bringing dreams to life!"
author: "Gala Events"
header:
 title: "Gala Events"
 subtitle: "galaendeavours@gmail.com"
footer:
 name: "Gala Events: End to End Wedding Planner"
 bio: "The Gala Events - Who we are :An End to End Wedding Planning and Management Company,  born out of passion for creativity and making Dreams come true in the year 2013.
       We handle End to End Wedding planning and management-PAN INDIA."
web_design: "GalaEvents"
social_urls:
  facebook: "https://www.facebook.com/Galaeventmanagers"
  instagram: "https://www.instagram.com/gala.weddings"
  youtube:   "https://www.youtube.com/channel/UCFL5WUt1q-jjg3Y9AlGyizA"
  linkedin: "https://in.linkedin.com/in/manisha-mehta-19565884"
